### ISSUE TITLE
Source for Linux Client

### ISSUE THREAD

**Issue by michalss** [sjourdan/hubic-configs#1]
Hi,

Is there any chance you could release a source code for your client for linux ? I would like to rewrite it into .core and use it. I know it is not for a new comming users but im using it very offen and need to do backups on Centos. Regards

**Comment by sjourdan** [comment]
unfortunately it's not my client, it was Hubic's a few years ago (I'm not sure it's maintained anymore as I heard the product is phased out)

cf https://forums.hubic.com/showthread.php?272-hubiC-for-Linux-beta-is-out-!

Good luck!
